Added shrug-show

diff --git a/shrug-show b/shrug-show
--- a/shrug-show
+++ b/shrug-show
@@ -2,6 +2,12 @@
 
 #init
 branch="master"
+commit_number=""
+file=""
+folder=""
+file_path=""
+is_commit_number_exist="false"
+is_in_index_folder="false"
 
 # error: shrug repository does not exist
 if [ ! -e ".shrug" ]
@@ -10,50 +16,77 @@ then
     exit 1
 fi
 
-#errors
-#TODO: 2041 shrug-show a.txt
-#shrug-show: error: invalid object a.txt
-#TODO: 2041 shrug-show 4:a.txt
-#shrug-show: error: unknown commit '4'
-#TODO: 2041 shrug-show 1:c.txt
-#shrug-show: error: 'c.txt' not found in commit 1
-#TODO: 2041 shrug-show
-#usage: shrug-show <commit>:<filename>
-#TODO: 2041 shrug-show 0 b.txt
-#usage: shrug-show <commit>:<filename>
+# error: number of arguements is not 1
+if [ $# -ne 1 ]
+then
+    echo "usage: shrug-show <commit>:<filename>"
+    exit 1
+fi
 
-#not error
-# condition: say I have not make any commit yet, only added a.txt and b.txt into the index folder
-#TODO: 2041 shrug-show :b.txt
-# 1
-# 2
-# 3
-# 4
-# 5
-#TODO: 2041 shrug-show 0:b.txt
-# shrug-show: error: unknown commit '0'
+# error: invalid input format
+echo $1 | grep -P -q ":"
+if [ $? -ne 0 ]
+then
+    echo "shrug-show: error: invalid object $1"
+    exit 1
+fi
 
-# condition: say I have made 1 commit, then made more changes to a.txt
-#TODO: 2041 shrug-show 0:a.txt
-# 1
-# 2
-# 3
-# 4
-# 5
-#TODO: seq 1 3 >> a.txt
-#TODO: 2041 shrug-add a.txt
-#TODO: 2041 shrug-show :a.txt
-# 1
-# 2
-# 3
-# 4
-# 5
-# 1
-# 2
-# 3
-#TODO: 2041 shrug-show 0:a.txt
-# 1
-# 2
-# 3
-# 4
-# 5
+# get commit number and file name
+commit_number=`echo $1 | cut -d":" -f1`
+file=`echo $1 | cut -d":" -f2`
+
+if [ -z $commit_number ]
+then
+    folder=".shrug/index"
+    is_in_index_folder="true"
+else
+    folder=".shrug/repo/$branch/$commit_number"
+fi
+
+# error: invalid file name format
+echo $file | grep -P -q "^[a-zA-Z0-9]+[.|-|_]"
+if [ $? -ne 0 ]
+then
+    echo "shrug-show: error: invalid filename '$file'"
+    exit 1
+fi
+
+# error: commit number does not exist
+for available_commit_number in `cat .shrug/repo/shrug.log | cut -d" " -f1`
+do
+    # check commit number is numeric 
+    echo $commit_number | grep -P -q "^[0-9]+$"
+    if [ $? -ne 0 ]
+    then
+        break
+    fi
+
+    # check commit number exist in log
+    if [ $commit_number -eq $available_commit_number ]
+    then
+        is_commit_number_exist="true"
+        break
+    fi
+done
+
+if [ $is_commit_number_exist = "false" -a $is_in_index_folder = "false" ]
+then
+    echo "shrug-show: error: unknown commit '$commit_number'"
+    exit 1
+fi
+
+# error: file does not exist in the target folder
+file_path="$folder/$file"
+if [ ! -e $file_path ]
+then
+    if [ $is_in_index_folder = "true" ] # no commit number, in the index folder
+    then
+        echo "shrug-show: error: '$file' not found in index"
+        exit 1
+    else # has commit number, in the repo folder
+        echo "shrug-show: error: '$file' not found in commit $commit_number"
+        exit 1
+    fi
+fi
+
+cat $file_path
