WIP: fixed a bug where temp file is not created before evaluate

diff --git a/shrug-rm b/shrug-rm
--- a/shrug-rm
+++ b/shrug-rm
@@ -65,12 +65,14 @@ then
     if [ $1 = "--force" -a $2 = "--cached" ]
     then
         is_format_valid="true"
+        is_option_cached_selected="true"
         is_option_force_selected="true"
     fi
 
     if [ $1 = "--cached" -a $2 = "--force" ]
     then
         is_format_valid="true"
+        is_option_cached_selected="true"
         is_option_force_selected="true"
     fi
 
@@ -112,6 +114,7 @@ do
 done
 
 # remove duplicated file names
+touch $temp_rm_print_file
 for file in $files
 do
     echo $file >> $temp_rm_print_file
@@ -119,7 +122,9 @@ done
 files=`sort $temp_rm_print_file | uniq`
 rm $temp_rm_print_file
 
-# [--cached] option: only remove files in the index folder
+# only remove files in the index folder
+# [--cached] with safety check
+# [--force] [--cached] without safety check
 if [ $is_option_cached_selected = "true" ]
 then
     # error: all files must exist in index, otherwise exit and o not delete any file
@@ -133,31 +138,34 @@ then
     done
 
     # check if file in current direcory is different from the one in index, otherwise exit and do not delete any file
-    for file in $files
-    do
-        is_diff_to_last_commit="false"
-        is_diff_to_cur_dir="false"
+    if [ $is_option_force_selected = "false" ]
+    then
+        for file in $files
+        do
+            is_diff_to_last_commit="false"
+            is_diff_to_cur_dir="false"
 
-        # check 1: compare index file with last commit (cannot have staged but uncommitted files)
-        last_commit_number=`cat $log_file | tail -n1 | cut -d" " -f1`
-        last_commit_folder=".shrug/repo/$commit_branch/$last_commit_number"
-        if ! cmp -s "$index_folder/$file" "$last_commit_folder/$file"
-        then
-            is_diff_to_last_commit="true"
-        fi
+            # check 1: compare index file with last commit (cannot have staged but uncommitted files)
+            last_commit_number=`cat $log_file | tail -n1 | cut -d" " -f1`
+            last_commit_folder=".shrug/repo/$commit_branch/$last_commit_number"
+            if ! cmp -s "$index_folder/$file" "$last_commit_folder/$file"
+            then
+                is_diff_to_last_commit="true"
+            fi
 
-        # chcek 2: compare content of each file (cannot have diff files in cur dir and index )
-        if ! cmp -s "$file" "$index_folder/$file"
-        then
-            is_diff_to_cur_dir="true"
-        fi
+            # chcek 2: compare content of each file (cannot have diff files in cur dir and index )
+            if ! cmp -s "$file" "$index_folder/$file"
+            then
+                is_diff_to_cur_dir="true"
+            fi
 
-        if [ $is_diff_to_cur_dir = "true" -a $is_diff_to_last_commit = "true" ]
-        then
-            echo "shrug-rm: error: '$file' in index is different to both working file and repository"
-            exit 1
-        fi
-    done
+            if [ $is_diff_to_cur_dir = "true" -a $is_diff_to_last_commit = "true" ]
+            then
+                echo "shrug-rm: error: '$file' in index is different to both working file and repository"
+                exit 1
+            fi
+        done
+    fi
 
     # remove file from index folder
     for file in $files
@@ -166,8 +174,10 @@ then
     done
 fi
 
-# [] or [--force] option: remove from both current directory and index folder
-if [ $is_option_cached_selected = "false" -o $is_option_force_selected = "true" ]
+# emove from both current directory and index folder
+# [] with safety check
+# [--force] without safety check
+if [ $is_option_cached_selected = "false" ]
 then
 
     # error: all files must exist in both current directory and index, otherwise exit and do not delete any file
diff --git a/shrug-status b/shrug-status
--- a/shrug-status
+++ b/shrug-status
@@ -16,7 +16,15 @@ then
     exit 1
 fi
 
+# error: repository does not have any commits yet
+if [ -z "`cat .shrug/repo/shrug.log`" ]
+then
+    echo "shrug-status: error: your repository does not have any commits yet"
+    exit 1
+fi
+
 # scan files from current directory
+touch $temp_status_print_file
 for file in `ls`
 do
     echo $file >> $temp_status_print_file
@@ -36,6 +44,13 @@ do
     echo $file >> $temp_status_print_file
 done
 
+# check if there is any file name that needs to display status, if not, exit
+if [ -z "`cat $temp_status_print_file`" ]
+then
+    exit 0
+fi
+
+# fi
 # remove duplicated file names
 files=`sort $temp_status_print_file | uniq`
 rm $temp_status_print_file
@@ -103,6 +118,20 @@ do
         is_file_changed="true"
     fi
 
+    # check if file is added to index
+    is_file_added_to_index="false"
+    if [ $is_file_exist_in_index = "true" -a $is_file_exist_in_last_commit = "false" ]
+    then
+        is_file_added_to_index="true"
+    fi
+
+    # check if file is deleted
+    is_file_deleted="false"
+    if [ $is_file_exist_in_cur_dir = "false" -a $is_file_exist_in_index = "true" -a $is_file_exist_in_last_commit = "true" ]
+    then
+        is_file_deleted="true"
+    fi
+
     # status: file changed, different changes staged for commit
     if [ $is_file_changed = "true" -a $is_file_diff_cur_dir_vs_index = "true" -a $is_file_diff_index_vs_last_commit = "true" ]
     then
@@ -124,12 +153,47 @@ do
         continue
     fi
 
+    # # status: added to index
+    # if [ $is_file_exist_in_cur_dir = "true" -a $is_file_exist_in_index = "true" -a $is_file_diff_cur_dir_vs_index = "false" -a $is_file_exist_in_last_commit = "false" ]
+    # then
+    #     echo "$file - added to index"
+    #     continue
+    # fi
+
+    # status: added to index, file changed
+    if [ $is_file_added_to_index = "true" -a $is_file_changed = "true" ]
+    then
+        echo "$file - added to index, file changed"
+        continue
+    fi
+
+    # status: added to index, file deleted
+    if [ $is_file_added_to_index = "true" -a $is_file_deleted = "true" ]
+    then
+        echo "$file - added to index, file deleted"
+        continue
+    fi   
+
+    # status: added to index
+    if [ $is_file_added_to_index = "true" ]
+    then
+        echo "$file - added to index"
+        continue
+    fi
+
     # status: file deleted
-    if [ $is_file_exist_in_cur_dir = "false" -a $is_file_exist_in_index = "true" -a $is_file_exist_in_last_commit = "true" ]
+    if [ $is_file_deleted = "true" ]
     then
         echo "$file - file deleted"
         continue
-    fi
+    fi   
+
+    # # status: file deleted
+    # if [ $is_file_exist_in_cur_dir = "false" -a $is_file_exist_in_index = "true" -a $is_file_exist_in_last_commit = "true" ]
+    # then
+    #     echo "$file - file deleted"
+    #     continue
+    # fi
 
     # status: deleted
     if [ $is_file_exist_in_cur_dir = "false" -a $is_file_exist_in_index = "false" -a $is_file_exist_in_last_commit = "true" ]
@@ -145,15 +209,9 @@ do
         continue
     fi
 
-    # status: added to index
-    if [ $is_file_exist_in_cur_dir = "true" -a $is_file_exist_in_index = "true" -a $is_file_diff_cur_dir_vs_index = "false" -a $is_file_exist_in_last_commit = "false" ]
-    then
-        echo "$file - added to index"
-        continue
-    fi
-
     # status: untracked
-    if [ $is_file_exist_in_cur_dir = "true" -a $is_file_exist_in_index = "false" -a $is_file_exist_in_last_commit = "false" ]
+    # if [ $is_file_exist_in_cur_dir = "true" -a $is_file_exist_in_index = "false" -a $is_file_exist_in_last_commit = "false" ]
+    if [ $is_file_exist_in_cur_dir = "true" -a $is_file_exist_in_index = "false" ]
     then
         echo "$file - untracked"
         continue
